brew "awscli"
brew "bat"
brew "cli53"
brew "fd"
brew "fzf"
brew "git-delta"
brew "gh"
brew "gnupg"
brew "htop"
brew "httpie"
brew "hub"
brew "jenv"
brew "k9s"
brew "kubectx"
brew "luajit", args: ['HEAD']
brew "neovim", args: ['HEAD']
brew "pinentry-mac"
brew "pyenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "thefuck"
brew "tmux"
brew "tree"
brew "urlview"
brew "vim"
brew "zsh"
tap "hashicorp/tap"
brew "hashicorp/tap/packer"

tap "homebrew/cask-fonts"
cask "font-hack-nerd-font"
cask "hyper"
cask "iterm2"
