syntax on

" Show line numbers
set number

set exrc " .vimrc in local project dir
set secure

" Enable 256 colors
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

