#!/bin/env zsh

# Uncomment this and the zprof line to enable profiling
# zmodload zsh/zprof

autoload -Uz compinit && compinit

[[ ! -f ~/.config/shell/common.sh ]] || source ~/.config/shell/common.sh
[[ ! -f ~/.config/shell/history.zsh ]] || source ~/.config/shell/history.zsh
[[ ! -f ~/.config/shell/antidote.zsh ]] || source ~/.config/shell/antidote.zsh
[[ ! -f ~/.config/shell/completions.zsh ]] || source ~/.config/shell/completions.zsh

zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':fzf-tab:*' use-fzf-default-opts yes

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(atuin init zsh)"
bindkey -M emacs '^[[A' atuin-up-search
bindkey -M viins '^[[A' atuin-up-search-viins
bindkey -M vicmd '^[[A' atuin-up-search-vicmd
bindkey -M emacs '^[OA' atuin-up-search
bindkey -M viins '^[OA' atuin-up-search-viins
bindkey -M vicmd '^[OA' atuin-up-search-vicmd

# zprof
