theme = "dracula"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [120]
end-of-line-diagnostics = "hint"
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.file-picker]
hidden = false

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
