#!/usr/bin/env bash

# Install devbox
if ! command -v devbox 2>&1 >/dev/null; then
  curl -fsSL https://get.jetify.com/devbox | bash
fi

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  BREW_EXE=$(/usr/bin/which /opt/homebrew/bin/brew || echo 0)
  if [ "$BREW_EXE" == "0" ]; then
    echo -e "🛠  Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    exit 1
  else
    echo -e "🛠  Updating brew"
    /opt/homebrew/bin/brew update >/dev/null 2>&1
  fi

  /opt/homebrew/bin/brew bundle check >/dev/null 2>&1 || {
    echo -e "🛠  Installing Homebrew dependencies…"
    /opt/homebrew/bin/brew bundle
  }
fi

devbox global install
