#!/usr/bin/env bash

set -e

# Bash color variables
COLOR_GREEN="\x1b[32;01m"
COLOR_RESET="\x1b[39;49;00m"

# Check that an executable exists
function executableCheck {
    local EXE=$1
    local NAME=$2
    if [ "$EXE" == "0" ]; then
        echo -e $COLOR_RED"💥  ${NAME} was not found. Check the installation requirements"$COLOR_RESET
        exit 1
    fi
}

echo -e "🚀  Bootstrapping @tagoro9 dotfiles..."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  # Install homebrew if it's not there
  BREW_EXE=$(/usr/bin/which brew || echo 0)
  if [ "$EXE" == "0" ]; then
    echo -e "🛠  Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    exit 1
  fi


  brew bundle check >/dev/null 2>&1  || {
    echo -e "🛠  Installing Homebrew dependencies…"
    brew bundle
  }

  # Set zsh as default terminal
  eval $(chsh -s /usr/local/bin/zsh)
fi

# Install oh-my-zsh if not there
OH_MY_ZSH=~/.oh-my-zsh
if [ ! -d "$OH_MY_ZSH" ]; then
  echo -e "🛠   Installing oh-my-zsh…"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Install vim-plug if not there
VIM_PLUG=~/.vim/autoload/plug.vim
if [ ! -f "$VIM_PLUG" ]; then
echo -e "🛠   Installing vim-plug…"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Install tpm if not there
TPM=~/.tmux/plugins/tpm
if [ ! -d "$TPM" ]; then
echo -e "🛠   Installing tmp…"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

echo -e $COLOR_GREEN"✅  Done\n"$COLOR_RESET
