#!/bin/env zsh

# Uncomment this and the zprof line to enable profiling
# zmodload zsh/zprof

# Init completions
autoload -Uz compinit && compinit

[[ ! -f ~/.config/shells/zsh/antidote.zsh ]] || source ~/.config/shells/zsh/antidote.zsh
[[ ! -f ~/.config/shells/common/common.sh ]] || source ~/.config/shells/common/common.sh

# Update fpath to include custom completions
fpath=( ~/.completions "${fpath[@]}" )

# fzf
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

# starship
eval "$(starship init zsh)"
# zoxide
eval "$(zoxide init zsh)"

# # sdkman
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# # Rust configuration
. "$HOME/.cargo/env"

# zprof