[[ ! -f ~/.config/shells/common/common.sh ]] || source ~/.config/shells/common/common.sh
[[ ! -f ~/.config/shells/zsh/zplug.zsh ]] || source ~/.config/shells/zsh/zplug.zsh

# Update fpath to include custom completions
fpath=( ~/.completions "${fpath[@]}" )

# Init completions
autoload -Uz compinit && compinit

# fzf
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

# starship
eval "$(starship init zsh)"
# zoxide
eval "$(zoxide init zsh)"

# sdkman
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# Python configuration
export PYENV_ROOT="$HOME/.pyenv"
if command -v pyenv 1>/dev/null 2>&1; then
 eval "$(pyenv init --path)"
fi

# GO configuration
export GOENV_ROOT="$HOME/.goenv"
export PATH="$GOENV_ROOT/bin:$PATH"
eval "$(goenv init -)"
