[settings]
idiomatic_version_file = true
idiomatic_version_file_enable_tools = ["go", "java", "node", "terraform"]

[tools]
bun = "1.4.1"
node = "24"
go = "1.27.1"
python = "3.14.7"
terraform = "1.16.1"
