name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pre-commit
        uses: open-turo/action-pre-commit@v3
      - name: Check release notes on pull_request
        if: github.event_name == 'pull_request'
        uses: open-turo/actions-release/lint-release-notes@v5
