name: Release

on:
  push:
    branches: [main, "v*"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Release
        id: release
        uses: open-turo/actions-release/semantic-release@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-plugins: |
            @open-turo/semantic-release-config
